name: Dometopia Stock Check

on:
  workflow_dispatch:  # 수동 실행을 허용

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl beautifulsoup4 selenium

    - name: Run script
      run: |
        python dmtopia.py  # 루트 디렉토리에 있는 dmtopia.py 파일 실행

    - name: Upload result to repository
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add 도매토피아_크롤링완료_.xlsx
        git commit -m "Auto-uploaded the crawling results"
        git push
