name: Run Selenium Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas beautifulsoup4 requests

    - name: Install Google Chrome 128
      run: |
        # Add Google's official GPG key
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

        # Add Google Chrome repository
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'

        # Install Google Chrome 128
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable=128.0.0.0-1

    - name: Move ChromeDriver to /usr/local/bin
      run: |
        # Move the uploaded ChromeDriver to /usr/local/bin
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run the script
      run: |
        python dmtopia.py
